# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [2]:
# Tu respuesta aquí
nombre = "Alejandro Taborda Henao"
edad = 27

print(f"Hola, me llamo {nombre} y tengo {edad} años.")


Hola, me llamo Alejandro Taborda Henao y tengo 27 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [3]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
# Primer y último elemento
print(f"El primer elemento es {numeros[0]} y el último elemento es {numeros[-1]}")


# Tres primeros elementos (slicing)
print(f"Los tres primeros elementos son: {numeros[:3]}" )

# Agregar 99 al final
numeros.append(99)
print(numeros)

El primer elemento es 10 y el último elemento es 15
Los tres primeros elementos son: [10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [4]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6:
    estado = "Aprobado"
else:
    estado = "Reprobado"

print(f"Nombre: {estudiante['nombre']}, Carrera: {estudiante['carrera']}, Promedio: {estudiante['promedio']} → {estado}")

Nombre: Carlos, Carrera: Sistemas, Promedio: 7.5 → Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [5]:
# Tu respuesta aquí
def calcular_area(base, altura):
    return (base * altura) / 2

area = calcular_area(5, 8)
print(area)

20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [6]:
# Tu respuesta aquí
cuadrados = [x**2 for x in range(1, 11)]

print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [12]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [13]:
# Tu respuesta aquí
# 1. Arreglo con valores dados
arr1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo 1:", arr1)
print("Shape:", arr1.shape)
print("Dtype:", arr1.dtype)

# 2. Matriz de ceros 3x4
arr2 = np.zeros((3, 4))
print("\nMatriz de ceros:\n", arr2)
print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)

# 3. Arreglo con linspace
arr3 = np.linspace(0, 1, 6)
print("\nArreglo linspace:", arr3)
print("Shape:", arr3.shape)
print("Dtype:", arr3.dtype)

Arreglo 1: [1.5 2.5 3.5 4.5]
Shape: (4,)
Dtype: float64

Matriz de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64

Arreglo linspace: [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [14]:
a = np.arange(1, 13)

# Tu respuesta aquí
# Convertir a matriz 3x4
matriz = a.reshape(3, 4)
print(matriz)

# Máximo, mínimo e índice del máximo
print("Máximo:", matriz.max())
print("Mínimo:", matriz.min())
print("Índice del máximo:", matriz.argmax())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Máximo: 12
Mínimo: 1
Índice del máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [15]:
# Tu respuesta aquí
# Crear dos arreglos aleatorios
a = np.random.randint(1, 21, 5)
b = np.random.randint(1, 21, 5)

print("Arreglo a:", a)
print("Arreglo b:", b)

# Operaciones elemento a elemento
print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)

Arreglo a: [10  3 20  6 20]
Arreglo b: [19  9 13  3  8]
Suma: [29 12 33  9 28]
Resta: [-9 -6  7  3 12]
Multiplicación: [190  27 260  18 160]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [16]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
print(f"Notas mayores o iguales a 6: {notas[notas >= 6]}")


Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
